name: Gatsby Build
on:
  push:
    branches:
    - '!master'
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # tag=v2
      - name: Log current commit hash
        run: |
          sed -i "s|GITHUB_COMMIT_URL_HERE|https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA|" src/layout/Layout.tsx
      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 16.x
      - name: Install dependencies
        run: yarn install --prod --pure-lockfile
#      This should be added in the long run
#      - name: Lint
#        run: yarn run lint
      - name: Build
        run: yarn run build
