name: Gatsby Build
on:
  push:
    branches:
    - '!master'
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Log current commit hash
        run: |
          sed -i "s|GITHUB_COMMIT_URL_HERE|https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA|" src/layout/Layout.tsx
      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 18.x
      - name: Install dependencies
        run: yarn install --prod --pure-lockfile
      - name: Build
        run: yarn run build
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 18.x
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn run lint
