name: Gatsby Publish
on:
  push:
    branches:
    - 'master'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Log current commit hash
        run: |
          sed -i "s|GITHUB_COMMIT_URL_HERE|https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA|" src/layout/Layout.tsx
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version: 18
      - uses: enriikke/gatsby-gh-pages-action@6293db9dd9d25701c5220c26a8716ac8322b6588 # v2
        with:
          access-token: x-access-token:${{ secrets.GITHUB_TOKEN }}
          deploy-branch: gh-pages
