name: Gatsby Publish
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log current commit hash
        run: |
          sed -i "s|GITHUB_COMMIT_URL_HERE|https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA|" src/layout/Layout.tsx
      - uses: enriikke/gatsby-gh-pages-action@fbe063b0cfaa8c16ec4e346cc3c48e9b154cce87  # v2.2.0
        with:
          access-token: x-access-token:${{ secrets.GITHUB_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
          skip-publish: ${{ !(github.event_name == 'push' && github.ref == 'refs/heads/master') }}
