name: Gatsby Publish
on:
  push:
    branches:
    - 'master'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
      - name: Log current commit hash
        run: |
          sed -i "s|GITHUB_COMMIT_URL_HERE|https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA|" src/layout/Layout.tsx
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: 18
      - uses: enriikke/gatsby-gh-pages-action@fbe063b0cfaa8c16ec4e346cc3c48e9b154cce87 # renovate: tag=v2
        with:
          access-token: x-access-token:${{ secrets.GITHUB_TOKEN }}
          deploy-branch: gh-pages
